version: '3'
services:

  tools:
    build:
      context: ../
      dockerfile: ./.docker/tools/Dockerfile
    volumes:
      - ..:/app
    env_file:
      - local.env

  client_api:
    build:
      context: ../
      dockerfile: ./.docker/client_api/Dockerfile
    volumes:
      - ../client_api:/app
    ports:
      - "80:8080"
    environment:
      DATABASE_URL: postgres://postgres:dev_pass@pg:5432
    env_file:
      - local.env

  # pg:
  #   image: postgres:14.4
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: dev_pass
  #   ports:
  #     - "5432:5432"

  # redis:
  #   image: redis:7.0.5
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   logging:
  #     driver: none
